### ISSUE TITLE
Strange comment behaviour

### ISSUE THREAD

**Issue by matklad** [alexeykudinkin/intellij-rust#103]
Consider the code and the caret position:

```Rust
fn main() {
<caret>//    92;    
}
```

When I press Enter, I get the following:

```Rust
fn main() {

    // <caret>//    92;
}
```

Not sure what is the expected outcome, but the `//` should not be duplicated. @Turbo87 please take a look :)

**Comment by Turbo87** [comment]
ouch, that is indeed wrong
