### ISSUE TITLE
Strip nested `testdata` directories

### ISSUE THREAD

**Issue by alexeykudinkin** [alexeykudinkin/intellij-rust#107]
As a followup of previous discussion [here](https://github.com/alexeykudinkin/intellij-rust/pull/96).

**Comment by alexeykudinkin** [comment]
@Turbo87, i'm not sure, that i've got how did you managed to mix tests with data on your screens?

**Comment by matklad** [comment]
In the project window (`Alt-1`) select `Packages` instead of `Project` in the top left corner. I did't know about it myself :)

**Comment by Turbo87** [comment]
![bildschirmfoto 2015-11-09 um 19 25 46](https://cloud.githubusercontent.com/assets/141300/11042486/b3c12c1a-8717-11e5-8d6a-14958fcc6d9e.png)

Use the "Packages" instead of the "Projects" tab

**Comment by Turbo87** [comment]
makes me wonder who of us is working for JetBrains... :stuck_out_tongue_winking_eye:

**Comment by matklad** [comment]
@Turbo87 I always `C-x f` to find my files, don't use Project view too much ;)

**Comment by alexeykudinkin** [comment]
We're secretly using NetBeans (what else!) internally. :stuck_out_tongue_winking_eye:

**Comment by Turbo87** [comment]
:joy:

**Comment by alexeykudinkin** [comment]
@matklad @Turbo87 seems like a valid scenario, let's just rename it to `cases` or something, not `testdata`.

`testData/org/rust/lang/.../testdata` seems bogus.

**Comment by Turbo87** [comment]
maybe just `test` to make it even shorter?

**Comment by matklad** [comment]
May be `fixtures`? It may be usefull in find file by name, because it does not have a `test` in it?

**Comment by Turbo87** [comment]
:+1: for `fixtures`

**Comment by alexeykudinkin** [comment]
:+1: for `fixtures`

`test` -- is ambigous with tests' root.

**Comment by matklad** [comment]
The longest options wins: it is Java ;)
