### ISSUE TITLE
Highlighting of the resolve result

### ISSUE THREAD

**Issue by matklad** [alexeykudinkin/intellij-rust#112]
Also I've figured out that a in let mut a = ... is not highlighted properly (with light blue background) when I place the curet on some reference of a like in the next snippet

```Rust
let mut a = 1;
let b = <caret>a;
```

~~The highlighting works for function arguments though.~~ The highlighting works if there is no `mut` keyword.

**Comment by pavel-v-chernykh** [comment]
Related #109 [comment](https://github.com/alexeykudinkin/intellij-rust/pull/109#issuecomment-155405662)

**Comment by Turbo87** [comment]
it seems that the reference is correctly (?) resolved to the `RustPatBinding` node in any case, but somehow the highlighting is not applied to it if `mut` is included

**Comment by matklad** [comment]
another test case

```Rust
type EventLoop = mio::EventLoop<Server>;

type T = EventLoop;
```

**Comment by Turbo87** [comment]
but that's not a local variable, right?!

**Comment by matklad** [comment]
Yep, changed the title ;)

**Comment by Turbo87** [comment]
#126 has a similar issue for mut vars btw. usages for `let <caret>a = 1` and `let <caret>mut a = 1` work but `let mut <caret>a = 1` fails
