### ISSUE TITLE
Demo text in RustColorSettingsPage is not annotated

### ISSUE THREAD

**Issue by himikof** [alexeykudinkin/intellij-rust#114]
Because of that, `println!` macro is wrongly highlighted as an identifier, not a macro invocation. There is no attributes or type parameters in the example rust code, but they are presumably broken too.
At the very least, if this settings page allows customizing macro invocation appearance, the example rust  code should respect that.

**Comment by matklad** [comment]
Documentation for `getDemoText` explains what is need to be done: https://upsource.jetbrains.com/idea-community/file/34e9f922b26ee27241fb671840ae931875fcacca/platform%2Flang-api%2Fsrc%2Fcom%2Fintellij%2Fopenapi%2Foptions%2Fcolors%2FColorSettingsPage.java?nav=stub:31:focused
