### ISSUE TITLE
Local variable highlighting for redeclared variables

### ISSUE THREAD

**Issue by Turbo87** [alexeykudinkin/intellij-rust#120]
```rust
fn main() {
    let x = 5;
    let x = x<caret> + 1;
}
```

In this case it should hightlight the first and third `x`, but not the second, because the second is a new binding. Instead if currently highlights the second and third, but not the first.

**Comment by matklad** [comment]
Ouch, haven't thought about this case. Currently, the scope inside a block is determined based solely on textual offset.

 https://github.com/alexeykudinkin/intellij-rust/blob/master/src/org/rust/lang/core/resolve/RustResolveEngine.kt#L69

**Comment by matklad** [comment]
fixed by #138

**Comment by Turbo87** [comment]
this doesn't seem to work for something like `let a = format!("foo {}", a);` yet, but I suppose that is related to the use of a macro here.

**Comment by matklad** [comment]
@Turbo87 Yes. The problem with macros is that after `foo!` you can have any token sequence as long as it has balanced parenthesis. So, theoretically, we can't infer that this `a` is, in fact, expression. 

The simlest strategy here is to support the most common macros on a case by case basis. Currently, the `try!` macro is supported. println! like macros should be next.

**Comment by Turbo87** [comment]
@matklad isn't it possible to parse the macro and replace the macro call with the macro content during resolution?

**Comment by matklad** [comment]
It should be possible for some cases, but it is hard becase:
   * you need to reilmplement rust's macro system in Kotlin,
   * you may need to tweak the parser, which is hard for a generated one. At least in rustc, parsing and macro expansion are somewhat entangled. 

And even this approach won't solve everything, becase there are pocedural macros, aka compiler plugins. To interpret them we will need a Rust interpreter in Kotlin, which is a bit of an overkill :)


Another possible approach is to add some options to `rustc` or future rust `oracle` specialy tailord for the usecase of explaining macro meaning to the IDE.
