### ISSUE TITLE
Intention: convert current module to directory module.

### ISSUE THREAD

**Issue by matklad** [alexeykudinkin/intellij-rust#123]
Every module in Rust starts as a single file like `src/util/foo.rs`. But after a while it grows a couple of structs, a dozen of impls, and you want to split it over several submodules. The first step to do so is to convert `src/util/foo.rs` to `src/util/foo/mod.rs`.

Lets create an action for this!

It does not need any PSI interaction, it can be defined purely in terms of files and directories.  Don't forget to add it to `doc/Usage.md`

**Comment by Turbo87** [comment]
good idea, I might have a look at that

**Comment by pavel-v-chernykh** [comment]
@Turbo87 have you already started?

**Comment by Turbo87** [comment]
Nope

**Comment by pavel-v-chernykh** [comment]
@Turbo87 If you don't mind, I would like to work on it

**Comment by Turbo87** [comment]
@pavel-v-chernykh if you include something like "Resolves #123" in the PR description the issue will automatically be closed once the PR is merged :wink:

**Comment by pavel-v-chernykh** [comment]
@Turbo87 thanks, will try to do next time

**Comment by pavel-v-chernykh** [comment]
@atsky @matklad please, close this issue
