### ISSUE TITLE
Update build instructions in README.md to match CONTRIBUTING.md

### ISSUE THREAD

**Issue by rambocoder** [alexeykudinkin/intellij-rust#137]
New users will not be able to build the plug-in when using steps in README.md because those instructions in are outdated unlike the updated ones in CONTRIBUTING.md.

**Comment by matklad** [comment]
Hm, what problems are you facing? 

Instructions in README.md are up-to-date. They don't include `--recursive` flag, because you need ctrs only for tests.

**Comment by rambocoder** [comment]
Hmm, going to close this issue. It wasn't building on one of my machines following the README.md, but now it is.
