### ISSUE TITLE
Can't build it on OS X 10.11.1

### ISSUE THREAD

**Issue by e-oz** [alexeykudinkin/intellij-rust#143]
```
compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> invalid source release: 1.8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7 mins 45.798 secs
```

Also, please ask if user is ready to download few hundred megabytes before doing it.

**Comment by matklad** [comment]
Thanks for the report! Please note that there is no even an alpha version of the plugin yet, and building from source naturally has it's rough edges. I will end a not about huge download size to the README right away :)

Do you have Java 8 installed?

**Comment by e-oz** [comment]
Yes, Java 8 Update 65, was pre-installed by default with OS.

**Comment by matklad** [comment]
And what is the output of `./gradlew --version`?

**Comment by e-oz** [comment]
```
------------------------------------------------------------
Gradle 2.8
------------------------------------------------------------

Build time:   2015-10-20 03:46:36 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_67 (Oracle Corporation 24.65-b04)
OS:           Mac OS X 10.11.1 x86_64
```

**Comment by e-oz** [comment]
And it's the system Java window: 
<img width="707" alt="screenshot 2015-11-17 03 33 49" src="https://cloud.githubusercontent.com/assets/526352/11199144/172fa8fc-8cdc-11e5-9f5d-064010bf6dd7.png">

**Comment by matklad** [comment]
This line says that gradle picks Java 7:

```
JVM:          1.7.0_67 (Oracle Corporation 24.65-b04)
```

I think `JAVA_HOME` environmental variable points to the older version of Java in your case.

**Comment by matklad** [comment]
I'm not sure what is the correct way to override JAVA_HOME for OS X, but [this](http://stackoverflow.com/questions/33046697/why-i-am-not-able-to-see-the-java-home-path-on-my-mac-os-x-10-11) seems reasonable.

**Comment by e-oz** [comment]
yes, thanks for help, looks like Java SDK was different version. As not Java programmer I didn't know the difference between SDK and runtime :)
Now build compiled successfully.

**Comment by alexeykudinkin** [comment]
@e-oz building from sources supposed to suit the needs of the developer not the end-user. If you're not ready to download few handred megabytes of dependencies -- just don't build it.

Unfortunately there is still no way to get it except to build it from sources. But that wouldn't last long.

**Comment by e-oz** [comment]
@alexeykudinkin If I don't know what size I should download, I can't say if I'm ready or not. Thanks for adding this info into readme.

**Comment by alexeykudinkin** [comment]
@e-oz you can always make a `--dry-run` with gradle prior to firing it.
