### ISSUE TITLE
TOML: forbid newlines in inline tables

### ISSUE THREAD

**Issue by matklad** [alexeykudinkin/intellij-rust#34]
Inline tables in TOML format must be on a single line: https://github.com/toml-lang/toml#inline-table

Current parser is whitespace insensitive and accepts multiline tables. 

It may be tricky to handle this on a parser level. An easy solution is to handle this via an annotator.

Docs:
http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/syntax_highlighting_and_error_highlighting.html

**Comment by pavel-v-chernykh** [comment]
Looks like closed by #76

**Comment by matklad** [comment]
Yep
