### ISSUE TITLE
getIdentifier() missing from RustTraitItem interface

### ISSUE THREAD

**Issue by Turbo87** [alexeykudinkin/intellij-rust#51]
It seems that the `RustTraitItem` interface has no `identifier` property like e.g. the `RustStructItem`. Am I missing something?

This is sort of required for #48.

**Comment by matklad** [comment]
Strange, it should be there...

@alexeykudinkin should know more.

**Comment by Turbo87** [comment]
could it be related to `IDENTIFIER` being included twice in https://github.com/alexeykudinkin/intellij-rust/blob/master/src/org/rust/lang/core/grammar/rust.bnf#L449-L452?

**Comment by matklad** [comment]
It could. Try removeing `private` from `for_sized`

**Comment by matklad** [comment]
Yes, just remove private.

Use `generateParsers` gradle task to regenerate PSI
