### ISSUE TITLE
IntelliJ version

### ISSUE THREAD

**Issue by syl123** [alexeykudinkin/intellij-rust#68]
Can you please indicate for which version of IntelliJ this plugin is compatible ?

Thanks

**Comment by atsky** [comment]
IntelliJ IDEA 15

**Comment by alexeykudinkin** [comment]
Yeah, we're currently targeted at the IDEA 15, though there're no other binding dependency except the Kotlin runtime, so you could use IDEA 14 with the Kotlin plugin (at least) 1-beta-038.

**Comment by himikof** [comment]
Maybe now it's a good idea to change `ideaVersion` in gradle.properties from `LATEST-EAP-SNAPSHOT` to a stable released IDEA 15 version?

**Comment by alexeykudinkin** [comment]
@himikof already!
