### ISSUE TITLE
Use TOML file type for Cargo.lock files

### ISSUE THREAD

**Issue by matklad** [alexeykudinkin/intellij-rust#80]
Because Cargo.lock is TOML

**Comment by pavel-v-chernykh** [comment]
Does anybody work on that?
I would like to play with it now.

**Comment by matklad** [comment]
@pavel-v-chernykh it's yours =)

**Comment by Turbo87** [comment]
have fun ;)

**Comment by pavel-v-chernykh** [comment]
@atsky looks like closed by #84
