### ISSUE TITLE
Highlight "mut" keyword

### ISSUE THREAD

**Issue by Turbo87** [alexeykudinkin/intellij-rust#89]
It might be a good idea to highlight the `mut` keyword in a different color than the other keywords. I've seen this in a presentation of @steveklabnik lately and thought that it emphasized the mutability of the variables quite well.

**Comment by Turbo87** [comment]
![bildschirmfoto 2015-11-08 um 10 13 58](https://cloud.githubusercontent.com/assets/141300/11019633/76c0f2a8-8601-11e5-8d8d-e7c1dcad9f24.png)

I have a patch ready for this, but it depends on #93 being merged first.

**Comment by matklad** [comment]
@alexeykudinkin @atsky @Turbo87  what do you think about highlighting not the `mut` keyword, but the  binning itself? That is highlighting all `compoents` and `ret` in the function? I guess it should be possible now, as we can resolve local variables.

**Comment by Turbo87** [comment]
@matklad I thought about that too, might also be a good idea. I guess that is similar to how the `val` vs `var` highlighting of Kotlin works.

**Comment by atsky** [comment]
I like idea of highlighting variable instead of `mul` like it done in Kotlin.

**Comment by alexeykudinkin** [comment]
:+1:

**Comment by pavel-v-chernykh** [comment]
:+1: for Kotlin style highlighting

**Comment by pavel-v-chernykh** [comment]
@Turbo87 If you don't mind I would like to work on that issue. Most likely tomorrow.

**Comment by pavel-v-chernykh** [comment]
@Turbo87 Oops, just realised that you already have patch

**Comment by Turbo87** [comment]
I have a patch for highlighting the mut keyword, not for highlighting the variables. Feel free to take it.

**Comment by pavel-v-chernykh** [comment]
@Turbo87 I've looked at Kotlin plugin implementation of mutable variable highlighting. And now I'm not ready to implement it in such a way. https://github.com/JetBrains/kotlin/blob/3bd7f87d2b1662374847f8bb95f0e9b1ebfa101c/idea/idea-analysis/src/org/jetbrains/kotlin/idea/highlighter/VariablesHighlightingVisitor.java#L98-L98

I think at current stage I could highlight it just in place of binding declaration and earlier at usage places.

**Comment by matklad** [comment]
>I think at current stage I could highlight it just in place of binding declaration and earlier at usage places.

Did you mean later? Binding comes before the usage. 

>And now I'm not ready to implement it in such a way.

I think we should not worry much about performance and a perfect architecture at the current stage. As long as we have a comprehensive test suite, refactoring is not a problem.

**Comment by pavel-v-chernykh** [comment]
@matklad Ok got it. Will try to do it.

**Comment by pavel-v-chernykh** [comment]
@matklad might be closed by #109

**Comment by matklad** [comment]
yep, thanks
