### ISSUE TITLE
Have no access to identifier in item_macro rule

### ISSUE THREAD

**Issue by pavel-v-chernykh** [alexeykudinkin/intellij-rust#98]
I've highlighted macro invocations (see #97). I want to do the same for ```macro_rules!``` but it is parsed by rule ```item_macro```:

```
item_macro ::= IDENTIFIER EXCL IDENTIFIER?
             ( LPAREN token_tree? RPAREN SEMICOLON
             | LBRACE token_tree? RBRACE
             | LBRACK token_tree? RBRACK SEMICOLON )
```

There is no accessor for the IDENTIFIER in current implementation of the ```RustItemMacro``` (only to EXCL).

Need accessor for IDENTIFIER to highlight it in the same way it is done for macro invocations.

Please, provide accessor for IDENTIFIER in ```item_macro``` rule.

**Comment by pavel-v-chernykh** [comment]
@matklad could you help me with this issue?

**Comment by Turbo87** [comment]
@pavel-v-chernykh I've noticed that often you can use the `name` property instead of the identifier, but I'm not sure how robust that solution actually is.

**Comment by pavel-v-chernykh** [comment]
@Turbo87 Don't understand what you mean. AFAIK to make an annotation instance of ```ASTNode``` or ```PsiElement``` is required. But ```name``` is a ```String```. Please, clarify your suggestion.

**Comment by Turbo87** [comment]
ah right, nevermind

**Comment by pavel-v-chernykh** [comment]
Ok, np

**Comment by matklad** [comment]
close, because irrelevant at the moment. Item level macros have more severe problems then a missing identifier.
